### ISSUE TITLE
interfaceSetup

### ISSUE THREAD

**Issue by Regnhundar** [kforsl/fullstack-ruby-rabbits#42]
Som utvecklare vill jag ha gedigna interfaces så det blir lättare att skriva kod.

- [ ] Styr upp interfaces för vårt api.
>- [x] Product
>- [x] Ingredient
>- [x] Inventory
>- [x] Allergen
>- [x] Order
>- [ ] Customer
>- [x] Employee
>- [ ] Discount

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement interfaces for Product, Ingredient, Inventory, Allergen, Order, Customer, Employee, and Discount models to improve code structure and maintainability.

You can review changes in this commit: https://github.com/lattaai13/kforsl-fullstack-ruby-rabbits-42/commit/4a44395ee3f87c95257ad5d9899c4000003d4309.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
